default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: pgdev
  password: developer

development:
  <<: *default
  database: pgdev

test:
  <<: *default
  database: pgdev

production:
  <<: *default
  database: pgdev
